### ISSUE TITLE
Parameters after the program name

### ISSUE THREAD

**Issue by beimzhan** [lasantosr/intelli-shell#4]
##### ISSUE
Hello, @lasantosr! All my commands that I run after receiving them from `intelli-shell` fall due to such an error:
```console
$ dconf list 
error: no command specified
```

If I get the command back with the up arrow, and execute it again, then everything works.

Second example:
```console
$ docker ps --all

Usage:  docker [OPTIONS] COMMAND
```

Third example:
```console
$ ps aux
    PID TTY          TIME CMD
  11720 pts/0    00:00:00 bash
  11890 pts/0    00:00:00 ps
```

Tried this in the `ubuntu:latest` container from `docker` and it works great!

##### ENVIRONMENT
OS: Fedora 37
Shell: GNU bash, version 5.2.15(1)-release (x86_64-redhat-linux-gnu)

**Comment by beimzhan** [comment]
The mentioned Docker container:
```Dockerfile
FROM ubuntu:latest
WORKDIR /app
RUN apt-get update && apt-get install -y curl
COPY install.sh .
RUN ./install.sh
RUN /root/.local/share/intelli-shell/bin/intelli-shell fetch
```

**Comment by lasantosr** [comment]
It seems like a bug with Bash 5.2 given that it has some [readline changes](https://git.savannah.gnu.org/cgit/bash.git/tree/NEWS), it also happens on `ubuntu:23.10`.

The bug is related to bash integration on [intelli-shell.sh](https://github.com/lasantosr/intelli-shell/blob/main/intelli-shell.sh) not on the program itself, so if any bash-expert can help us here it would be great!

I'll have a look when i have some time, but i'm no expert.

**Comment by beimzhan** [comment]
Thanks, bug fixed. Very useful program!
