### ISSUE TITLE
[feature request] No support for multiline scripts

### ISSUE THREAD

**Issue by dj8yfo** [lasantosr/intelli-shell#8]
```
intelli-shell 0.2.3
in zsh 5.9
```
I tried to use it for following script to try to take advantage of labels' expanding functionality
```zsh
cd {{ part_dir }}
inotifywait -e close_write,moved_to,create -m . |
while read -r directory events filename; do
  if [ "$filename" = {{ file_name_quoted }} ]; then
    bash {{ file_name }}
  fi
done
```

And it produced the following output
```zsh
cd  part_dir inotifywait -e close_write,moved_to,create -m . |while read -r directory events filename; doif [ "$filename" = "filename.sh" ]; thenbash filename.shfidone
```
Maybe, adding support for multiline is a bit over the top, and the program was never intended to be used in such way, but i created an issue nevertheless, just in case)

**Comment by lasantosr** [comment]
Multi-line is supported when creating a new command, both from paste and current line buffer, by removing the newlines and flattening the content. Note that the content must work when placed in a single line.

I guess some semicolons `;` are missing on your statement, that's why it doesn't work when executed in a single line:

``` sh
cd {{ part_dir }};
inotifywait -e close_write,moved_to,create .....
```

I'm afraid the tool is not designed to show multiline statements, just to keep it simple and to be able to display multiple commands when searching, but it should work for your use case (some improvements were made on 51e9694, but not really needed)

**Comment by dj8yfo** [comment]
@lasantosr Yes, adding a bunch of `;` helped. 
But still, you should consider multiline scripts support (imho). 
The only problem that stays is that input is mangled into single line, though the template is saved allright.
Its hard to understand what the original script meant, though the labels in template are populated pretty awesome.
